### ISSUE TITLE
Создать основу для tpc-core

### ISSUE THREAD

**Issue by Reversean** [TouchTheGrass/tpc-core#1]
Создать базовое приложение на Django

- все, что должно делать приложение, это запускаться
- в репозитории должно находиться только то, что необходимо для запуска
- все ненужные файлы и папки, появляющиеся в ходе разработки, должны быть добавлены в `.gitignore`
- составить `README.md` с кратким гайдом по запуску приложения

**Comment by Reversean** [comment]
- Не надо заносить проект в отдельную папку, перемести проект в корень.
- Для чего нужен сейчас файл [db.sqlite3](https://github.com/TouchTheGrass/tpc-core/blob/guliev/base-app/base/db.sqlite3)?
- [README.md](https://github.com/TouchTheGrass/tpc-core/blob/guliev/base-app/README.md) на русском оставь.

**Comment by GulievEG** [comment]
1. Проект автоматически заносится в отдельную папку. Посмотрю, как перемести проект в корень.
2. БД автоматически создается при первом запуске приложения. Я сделал запуск сервера перед пушом.
3. Хорошо. Верну на русский язык.
